# welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([3,6,34,7])

In [3]:
myarr

array([ 3,  6, 34,  7])

In [4]:
myarr = np.array([[3,6,34,7,23,1]],np.int64)

In [6]:
myarr[0,2]

34

In [7]:
myarr.shape

(1, 6)

In [8]:
myarr[0,2]=43

In [9]:
myarr[0,2]

43

In [10]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [16]:
zeros =np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
rng = np.arange(10)

In [20]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
lin_space = np.linspace(1,5,12) # 1 se 5 ka bick 12 no 

In [24]:
lin_space

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
emp = np.empty((4,6))

In [26]:
emp

array([[6.23042070e-307, 1.42417221e-306, 1.37961641e-306,
        1.00132483e-307, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 8.90092016e-307,
        1.02361342e-306, 6.89804133e-307, 8.90104239e-307],
       [8.90098127e-307, 8.90111708e-307, 6.23054633e-307,
        8.90111708e-307, 6.89806849e-307, 8.90104239e-307],
       [1.42417221e-306, 1.95820216e-306, 1.69120552e-306,
        6.89807188e-307, 9.34598926e-307, 2.56765117e-312]])

In [27]:
emp_like = np.empty_like(lin_space)

In [28]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [31]:
ide = np.identity(5)

In [32]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
ide.shape

(5, 5)

In [34]:
x= [[1,2,3],[4,5,6],[7,1,0]]

In [35]:
ar = np.array(x)

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [37]:
ar.sum(axis=0)

array([12,  8,  9])

In [38]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [39]:
ar.T  # transpose arr

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [41]:
ar.flat

In [44]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [45]:
one = np.array([2,3,4,5,67,85])

In [46]:
one.argmax()

5

In [48]:
one.argmax

<function ndarray.argmax>

In [49]:
one.argmin()

0

In [50]:
ar2= [[1,2,3],[4,5,6],[7,1,0]]

In [51]:
ar+ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [52]:
ar*ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [53]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [54]:
ar.sum()

29

In [55]:
ar.min()

0

In [58]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [59]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))