# NumPy


**Creating NumPy Arrays**

**1-D Array**


In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

**2-D Array**

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [6]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

**3-D Array**

In [7]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [8]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Checking array properties

**arr.ndim  -> no. of dimension**

In [9]:
arr3.ndim

3

In [10]:
arr2.ndim

2

In [11]:
arr.ndim

1

**arr.shape  -> shape of arr (row, col)**

In [12]:
arr3.shape

(2, 2, 2)

In [13]:
arr2.shape

(2, 3)

In [14]:
arr.shape

(5,)

**arr.size  -> total no of element**

In [15]:
arr3.size

8

In [16]:
arr2.size

6

In [17]:
arr.size

5

**arr.dtype -> data type of element**

In [19]:
arr3.dtype

dtype('int32')

In [20]:
arr.dtype

dtype('int32')

In [21]:
arr2.dtype

dtype('int32')

# creating special array

**Zeros and Ones**

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Identity Matrix**

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

**Arange ( start, stop, step)**

In [26]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [27]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

**Linspace  (start, stop, num_points)**

In [28]:
np.linspace(0,4,15)

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        , 2.28571429, 2.57142857,
       2.85714286, 3.14285714, 3.42857143, 3.71428571, 4.        ])

In [30]:
np.linspace(1,4,4)

array([1., 2., 3., 4.])

In [31]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Random Array**


In [32]:
np.random.rand(3,3)

array([[0.96698947, 0.98228211, 0.44636702],
       [0.72411788, 0.52934446, 0.33114306],
       [0.46610391, 0.31853419, 0.93772108]])

In [33]:
np.random.randn(3,3)

array([[ 1.16090756,  0.502289  ,  1.55403696],
       [ 2.15188283, -0.27004911,  0.16024928],
       [-0.42101639,  0.10985645, -1.41612843]])

In [35]:
np.random.randint(1,100,(2,3))

array([[71, 89, 84],
       [11, 52, 30]])

# Mathematical Functions

**sqrt() square root**

In [38]:
x= np.array([2,3,4,5,6])

In [39]:
x

array([2, 3, 4, 5, 6])

In [40]:
np.sqrt(x)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974])

**exp() exponential**

In [41]:
np.exp(x)

array([  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ,
       403.42879349])

**log() logarithm**

In [42]:
np.log(x)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947])

**sin() sine**

In [43]:
np.sin(x)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

# Aggregation Function

**sum() - sum of elements**

In [44]:
np.sum(x)

20

**mean() - mean of elements**

In [45]:
np.mean(x)

4.0

**median() - median of elements**

In [46]:
np.median(x)

4.0

**std() - standard deviation**

In [47]:
np.std(x)

1.4142135623730951

**max() and min() - find max and min value of elements**

In [48]:
np.max(x)

6

In [49]:
np.min(x)

2

# Reshaping & Manipulating Arrays
**Reshape**

In [50]:
arr = np.arange(1,10).reshape(3,3)

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Flatten**

In [53]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Stacking**

In [55]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])



In [56]:
np.hstack([a, b])  # horizontal stack

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
np.vstack([a, b])  # Vertical stack

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

**Transpose**

In [63]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Copying & Views

**copy()**

In [65]:
arr = np.array([1, 2, 3])
copy_arr = arr.copy() 

In [66]:
copy_arr

array([1, 2, 3])

**view()**

In [67]:
rr = np.array([1, 2, 3])
view_arr = arr.view()

In [68]:
view_arr

array([1, 2, 3])

# Saving & Loading Data


**Save NumPy Arrays**

In [69]:
np.save('array.npy', arr)  # save as .npy
np.savetxt('array.txt', arr, delimiter=',')  # Save as text

**Loading NumPy Arrays**

In [70]:
np.load('array.npy')  # Load .npy file
np.loadtxt('array.txt', delimiter=',')  # Load text file


array([1., 2., 3.])

**Use np.where() for condition-based indexing**

In [74]:
arr = np.array([10, 20, 30, 40])
np.where(arr > 20, "more", "less")


array(['less', 'less', 'more', 'more'], dtype='<U4')

# Thank You 